[pytest]
markers =
    functional_positive: pruebas funcionales con flujo válido o esperado
    functional_negative: pruebas funcionales que validan errores o condiciones inválidas
    domain: pruebas específicas del dominio (validaciones de campos, relaciones o reglas de negocio)
    smoke: pruebas básicas para verificar el funcionamiento principal del sistema
    regression: conjunto completo de pruebas funcionales (positivas, negativas y de dominio) ejecutadas en ciclos de regresión para validar la estabilidad general del sistema tras cambios o despliegues

#------------------------LOGGING----------------------------
log_cli = 1

log_cli_level = DEBUG
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

log_level = DEBUG
log_format = %(asctime)s - %(levelname)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
#------------------------------------------------------------