[pytest]
markers =
    smoke: pruebas básicas para verificar funcionamiento principal
    high: Prioridad alta > pruebas críticas, si fallan bloquean el negocio
    medium: Prioridad media > pruebas importantes, su falla afecta pero no detiene el negocio
    low: prioridad baja > pruebas secundarias, su falla no impacta el negocio principal.